import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.min.css'

import TableComponent from '../components/table.component.jsx'

export default function Home() {
    return (
        <div className='bg-black'>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main></main>
            <TableComponent />
        </div>
    )
}
